name: HaitiCSS
markdown: kramdown

gems: ['jekyll-github-metadata']
repository: haiticss/haiticss.github.io

title: HaitiCSS
url: https://haiticss.io
enforce_ssl: haiticss.io

# HaitiCSS core path
haiticss-path: ../_haiticss/

# Google services
google_analytics: UA-97633338-1

# Collections
collections:
  docs-objects:
    output: true
    permalink: /docs/objects/:name
  haiticss:
    output: false